// import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Image from "next/image";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar"
import { AppSidebar } from "@/components/app-sidebar"


// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// `${geistSans.variable} ${geistMono.variable} antialiased

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  const username = "Justin";
  const LogoImage = '/LOGO.png'

  return (
    <html lang="en">
      <body>
        
          
        <header
         className="text-right p-4 flex justify-between bg-gradient-to-br from-orange-400 to-orange-700 items-center drop-shadow-lg">
          <Image src={LogoImage} width={100} height={100} alt="logo"/>
          <span className="font-bold text-white text-3xl">LC SIGN HELPDDESK</span>
          <div className="text-white">Logged in as <br /><span className="font-bold text-2xl">{username}</span></div>
        </header>
        <SidebarProvider >
          <AppSidebar />
            <SidebarTrigger />
            {children}
        </SidebarProvider>
        {/* <footer className="">
          Bye World
        </footer> */}
        
      </body>
    </html>
  );
}
